[package]
name = "rust-buch_testing"
version = "0.1.0"
authors = ["Marcel Koch <kontakt@marcelkoch.net>"]
edition = "2018"

[dependencies]
mockall = "0.9.1"
pretty_assertions = "0.6.1"
mockall_double = "0.2.0"
