[package]
name = "rustbuch_testing"
version = "0.1.0"
authors = ["Marcel Koch <m@rcelko.ch>"]
edition = "2018"

[dependencies]
mockall_double = "0.3.0"
mockall = "0.11.1"
k9 = "0.11.5"
insta = "1.15.0"

[dev-dependencies]
pretty_assertions = "1.2.1"
