[package]
name = "rust_buch_08_systemnah"
version = "0.1.0"
authors = ["Marco Amann <marco@amann.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"